-- ============================================================================
-- Seed: seed_articles.sql
-- Description: Insert article categories and educational articles for TIRTA app
-- ============================================================================

-- ============================================================================
-- 1. Article Categories (6 categories)
-- ============================================================================

INSERT INTO article_categories (name, slug, icon, color) VALUES
  ('Pengenalan TBC', 'pengenalan', '61838', '#1565C0'),
  ('Gejala TBC', 'gejala', '61894', '#E53935'),
  ('Penularan TBC', 'penularan', '61726', '#F57C00'),
  ('Pencegahan TBC', 'pencegahan', '62330', '#2E7D32'),
  ('Pengobatan OAT', 'pengobatan', '61912', '#6A1B9A'),
  ('Sosialisasi & Stigma', 'sosialisasi', '61197', '#00838F')
ON CONFLICT (slug) DO UPDATE SET icon = EXCLUDED.icon;

-- ============================================================================
-- 2. Articles (12 articles)
-- ============================================================================

-- Article 1: Pengenalan TBC (Featured)
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Apa Itu TBC? Kenali Penyakit dan Cara Mencegahnya',
  'apa-itu-tbc-kenali-penyakit-dan-cara-mencegahnya',
  'Tuberkulosis (TBC) adalah penyakit menular yang disebabkan oleh bakteri *Mycobacterium tuberculosis*. Meskipun sering dikaitkan dengan paru-paru, TBC juga bisa menyerang organ lain.',
  E'Tuberkulosis (TBC) adalah penyakit menular yang disebabkan oleh bakteri *Mycobacterium tuberculosis*. Penyakit ini sudah ada sejak ribuan tahun lalu dan hingga kini masih menjadi salah satu masalah kesehatan terbesar di dunia, termasuk di Indonesia.\n\n### Mengapa TBC Masih Jadi Masalah?\n\nIndonesia masuk dalam 8 negara dengan beban TBC tertinggi di dunia. Setiap tahun, diperkirakan terdapat lebih dari 800.000 kasus baru TBC di Indonesia. Ironisnya, banyak dari penderita ini tidak menyadari kondisinya hingga penyakit sudah dalam stadium lanjut.\n\n### TBC Bukan Hanya Menyerang Paru-Paru\n\nMeskipun TBC paru adalah bentuk yang paling umum (sekitar 80% kasus), bakteri TB juga dapat menyerang organ lain melalui aliran darah, kondisi ini disebut **TBC Ekstra Paru**, yang meliputi:\n- Kelenjar getah bening (limfadenitis TB)\n- Tulang belakang (spondilitis TB)\n- Otak (meningitis TB)\n- Ginjal\n- Payudara\n\n### Siapa yang Berisiko?\n\nTBC dapat menyerang siapa saja, namun kelompok berisiko tinggi meliputi:\n- Orang yang tinggal serumah dengan penderita TBC aktif\n- Penderita HIV/AIDS (sistem imun lemah)\n- Penderita diabetes mellitus\n- Perokok aktif\n- Orang yang tinggal di lingkungan padat dan kurang ventilasi\n- Kelompok usia produktif (15–50 tahun)\n- Anak-anak\n\n### Fakta Penting tentang TBC\n\n- TBC **BISA DISEMBUHKAN** dengan pengobatan yang tepat dan teratur selama 6–9 bulan\n- Deteksi dini adalah kunci keberhasilan pengobatan\n- Penderita TBC yang sudah berobat selama 2 minggu tidak lagi menularkan penyakit\n- Pengobatan TBC di Indonesia **GRATIS** melalui program pemerintah (DOTS)\n\n> **Ingat:** Semakin cepat TBC terdeteksi, semakin tinggi peluang kesembuhan dan semakin rendah risiko penularan ke orang-orang tercinta.',
  1, 5, TRUE
) ON CONFLICT (slug) DO NOTHING;

-- Article 2: Gejala TBC (Featured)
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Mengenal Gejala TBC Sejak Dini dan Cara Penanganannya',
  'mengenal-gejala-tbc-sejak-dini-dan-cara-penanganannya',
  'Banyak penderita TBC tidak menyadari bahwa mereka sakit karena gejala awalnya mirip batuk biasa. Mengenal gejala sejak dini sangat penting untuk mencegah penyebaran.',
  E'Salah satu tantangan terbesar dalam penanganan TBC adalah banyak penderita yang tidak menyadari bahwa mereka terinfeksi. Gejala awal TBC sering dianggap sebagai batuk biasa atau masuk angin, sehingga pengobatan terlambat dilakukan.\n\n### Gejala Utama TBC\n\n**Batuk Lebih dari 2 Minggu**\nIni adalah gejala paling utama dan paling sering diabaikan. Batuk pada TBC bersifat persisten (tidak kunjung sembuh), bisa berdahak maupun kering. Batuk yang berlangsung lebih dari 2 minggu dan tidak membaik dengan obat batuk biasa harus segera diperiksa.\n\n**Batuk Berdarah atau Dahak Bercampur Darah**\nJika dahak bercampur darah atau kamu batuk mengeluarkan darah, ini adalah tanda serius yang memerlukan pemeriksaan segera ke dokter atau puskesmas.\n\n### Gejala Tambahan yang Sering Diabaikan\n\n| Gejala | Keterangan |\n|--------|------------|\n| Demam meriang | Suhu tubuh naik terutama sore hari, berlangsung >1 bulan |\n| Keringat malam | Berkeringat deras saat tidur meski tidak kepanasan |\n| Penurunan berat badan | Berat badan turun drastis tanpa diet atau alasan jelas |\n| Nafsu makan menurun | Tidak ada keinginan makan, badan terasa lemas |\n| Sesak napas | Terasa berat saat bernapas, terutama saat aktivitas |\n| Nyeri dada | Rasa nyeri atau tidak nyaman di area dada |\n| Lemas dan mudah lelah | Aktivitas ringan pun terasa melelahkan |\n\n### Tanda-tanda yang Harus Segera ke Dokter\n\n🚨 **Segera ke puskesmas atau rumah sakit jika:**\n- Batuk lebih dari 2 minggu tidak sembuh\n- Batuk mengeluarkan darah\n- Sesak napas makin memberat\n- Berat badan turun drastis dalam waktu singkat\n- Demam >1 bulan yang tidak jelas penyebabnya\n\n### Apa yang Harus Dilakukan?\n\n1. **Jangan tunda** — Segera kunjungi puskesmas terdekat\n2. **Bawa dahak** — Dokter akan meminta sampel dahak untuk diperiksa (tes BTA atau TCM)\n3. **Rontgen dada** — Pemeriksaan foto toraks untuk melihat kondisi paru\n4. **Ikuti instruksi dokter** — Jika positif TBC, mulai pengobatan OAT segera\n\n> "Deteksi dini adalah senjata paling ampuh melawan TBC. Semakin cepat terdeteksi, semakin tinggi tingkat keberhasilan pengobatan dan semakin rendah risiko penularan ke orang terdekat."',
  2, 4, TRUE
) ON CONFLICT (slug) DO NOTHING;

-- Article 3: Penularan TBC
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Bagaimana TBC Menular? Fakta yang Perlu Kamu Tahu',
  'bagaimana-tbc-menular-fakta-yang-perlu-kamu-tahu',
  'TBC menular melalui udara saat penderita batuk, bersin, atau berbicara. Memahami cara penularan membantu kita melindungi diri dan orang-orang di sekitar.',
  E'Tuberkulosis menyebar melalui udara — inilah yang membuat penyakit ini mudah menular di lingkungan yang padat. Namun, dengan pengetahuan yang tepat, penularan dapat dicegah secara efektif.\n\n### Mekanisme Penularan\n\nKetika seorang penderita TBC aktif (yang belum diobati atau sedang dalam fase menular) **batuk, bersin, berbicara, atau bernyanyi**, mereka melepaskan percikan kecil dahak ke udara yang disebut **droplet nuklei** (aerosol).\n\nSetiap kali batuk, seorang penderita TBC dapat melepaskan **sekitar 3.000 droplet nuklei** ke udara. Droplet ini sangat kecil dan ringan sehingga dapat melayang di udara selama beberapa jam, terutama di ruangan yang tidak berventilasi baik.\n\n### Kondisi yang Mempercepat Penularan\n\n- Ruangan tertutup dengan sirkulasi udara buruk\n- Kontak intens dan lama dengan penderita (serumah, ruang kerja, sekolah)\n- Penderita belum memulai pengobatan atau tidak patuh minum obat\n- Sistem imun orang yang terpapar sedang lemah\n\n### TBC TIDAK Menular Melalui:\n❌ Berjabat tangan\n❌ Berbagi makanan/minuman\n❌ Menyentuh benda yang sama\n❌ Toilet umum\n❌ Gigitan nyamuk atau serangga\n❌ Kontak kulit biasa\n\n### Kapan Penderita Tidak Lagi Menular?\n\nKabar baiknya: penderita TBC yang **sudah menjalani pengobatan OAT selama minimal 2 minggu** umumnya sudah tidak lagi menularkan penyakit kepada orang lain. Inilah mengapa memulai pengobatan sesegera mungkin sangat penting, bukan hanya untuk diri sendiri tetapi juga untuk melindungi orang-orang di sekitar.\n\n### Yang Harus Dilakukan Jika Terpapar\n\nJika kamu tinggal serumah atau sering berkontak dengan penderita TBC:\n1. Lakukan pemeriksaan tes TBI (Tuberculin Skin Test atau IGRA)\n2. Konsultasikan dengan dokter tentang perlunya terapi preventif\n3. Pantau gejala selama minimal 3 bulan\n4. Jaga ventilasi rumah dan paparan sinar matahari',
  3, 3, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 4: Pencegahan TBC
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Langkah Mudah Mencegah Penularan TBC di Rumah dan Lingkungan',
  'langkah-mudah-mencegah-penularan-tbc-di-rumah-dan-lingkungan',
  'Pencegahan TBC dimulai dari kebiasaan sederhana sehari-hari. Dari ventilasi rumah yang baik hingga vaksinasi BCG, semua bisa dilakukan untuk melindungi diri dan keluarga.',
  E'Mencegah TBC lebih baik daripada mengobatinya. Meski TBC bisa disembuhkan, proses pengobatannya panjang dan memerlukan komitmen tinggi. Berikut langkah-langkah konkret yang bisa kamu lakukan.\n\n### 1. Vaksinasi BCG\n\nVaksin BCG (Bacille Calmette-Guérin) adalah vaksin yang diberikan pada bayi baru lahir sebagai perlindungan awal dari TBC. Vaksin ini efektif mencegah TBC berat pada anak-anak, terutama meningitis TB dan TB milier yang dapat berakibat fatal.\n\n### 2. Jaga Ventilasi dan Paparan Sinar Matahari\n\n- Buka jendela setiap hari untuk sirkulasi udara segar\n- Biarkan sinar matahari masuk ke dalam rumah — sinar UV matahari dapat membunuh bakteri TB\n- Hindari ruangan lembab dan gelap\n- Pastikan kamar tidur mendapat cukup cahaya alami\n\n### 3. Etika Batuk dan Bersin\n\nJika kamu atau anggota keluarga mengalami batuk:\n- Tutup mulut dan hidung dengan tisu atau lengan bagian dalam\n- Buang tisu bekas ke tempat sampah tertutup\n- Cuci tangan setelah batuk atau bersin\n- Gunakan masker jika berada di tempat umum\n\n### 4. Pola Hidup Sehat\n\nSistem imun yang kuat adalah pertahanan terbaik melawan TBC:\n- Konsumsi makanan bergizi seimbang (protein, vitamin, mineral)\n- Tidur cukup 7–9 jam per malam\n- Olahraga teratur minimal 30 menit/hari\n- Hindari rokok dan alkohol\n- Kelola stres dengan baik\n\n### 5. Skrining Kontak Erat\n\nJika ada anggota keluarga yang didiagnosis TBC:\n- Semua anggota rumah tangga (terutama anak <5 tahun) wajib diperiksa\n- Lakukan pemeriksaan dahak dan rontgen dada\n- Diskusikan dengan dokter tentang terapi pencegahan (TPT/Terapi Preventif TB)\n\n### 6. Terapi Preventif TB (TPT)\n\nBagi orang-orang yang berisiko tinggi (kontak erat dengan penderita TBC, ODHIV, dll.), dokter mungkin merekomendasikan **Terapi Preventif TB** — pemberian obat isoniazid selama 6 bulan untuk mencegah infeksi TB berkembang menjadi penyakit aktif.',
  4, 4, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 5: Pengobatan OAT
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Pentingnya Minum Obat TBC Secara Teratur Tanpa Putus',
  'pentingnya-minum-obat-tbc-secara-teratur-tanpa-putus',
  'Pengobatan TBC membutuhkan komitmen 6–9 bulan minum obat tanpa putus. Berhenti di tengah jalan bukan hanya berbahaya bagi diri sendiri, tapi juga bagi masyarakat.',
  E'Salah satu tantangan terbesar dalam penanganan TBC bukan hanya diagnosis, melainkan kepatuhan pengobatan. Banyak pasien yang berhenti minum obat saat merasa sudah membaik — padahal ini adalah keputusan yang sangat berbahaya.\n\n### Apa Itu OAT?\n\n**OAT (Obat Anti Tuberkulosis)** adalah kombinasi beberapa jenis antibiotik yang diberikan untuk membasmi bakteri *Mycobacterium tuberculosis* secara tuntas. Pengobatan OAT di Indonesia tersedia **GRATIS** di seluruh puskesmas dan rumah sakit pemerintah melalui program DOTS (Directly Observed Treatment Short-Course).\n\n### Fase Pengobatan OAT\n\n**Fase Intensif (2 Bulan Pertama)**\n- 4 jenis obat: Isoniazid (H), Rifampisin (R), Pirazinamid (Z), Etambutol (E)\n- Minum setiap hari tanpa jeda\n- Bakteri dibasmi secara masif\n- Setelah 2 minggu, pasien umumnya sudah tidak menular\n\n**Fase Lanjutan (4–7 Bulan Berikutnya)**\n- 2 jenis obat: Isoniazid (H) dan Rifampisin (R)\n- Total durasi: 6 bulan untuk TBC biasa, 9 bulan untuk kasus tertentu\n\n### Mengapa Tidak Boleh Berhenti di Tengah Jalan?\n\n⚠️ **Bahaya jika pengobatan dihentikan sebelum selesai:**\n\n1. **Bakteri tidak mati sempurna** — Sisa bakteri yang masih hidup dapat berkembang biak kembali\n2. **TBC kambuh** — Penyakit dapat kembali aktif dalam beberapa bulan\n3. **Resistensi obat** — Bakteri yang bertahan dapat menjadi kebal terhadap obat (MDR-TB), yang jauh lebih sulit dan mahal diobati\n4. **Bahaya bagi masyarakat** — TBC yang resisten dapat menular ke orang lain dan sulit ditangani\n\n### Efek Samping OAT dan Cara Mengatasinya\n\n| Efek Samping | Penyebab | Cara Mengatasi |\n|---|---|---|\n| Urine berwarna oranye/merah | Rifampisin | Normal, tidak berbahaya |\n| Mual dan muntah | Pirazinamid | Minum obat setelah makan |\n| Kulit gatal/kemerahan | Isoniazid | Konsultasi dokter segera |\n| Kesemutan di tangan/kaki | Isoniazid | Suplemen Vitamin B6 |\n| Gangguan penglihatan | Etambutol | Segera hubungi dokter |\n\n### Tips Patuh Minum OAT\n\n✅ Minum obat di jam yang sama setiap hari\n✅ Gunakan pengingat alarm atau aplikasi\n✅ Libatkan anggota keluarga sebagai PMO (Pengawas Minum Obat)\n✅ Simpan obat di tempat yang mudah dilihat\n✅ Catat setiap kali minum obat di buku harian\n✅ Jangan lewatkan kontrol ke puskesmas\n\n> **Ingat:** Menyelesaikan pengobatan OAT hingga tuntas adalah bentuk tanggung jawab pada diri sendiri dan orang-orang di sekitar kamu.',
  5, 5, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 6: Gejala TBC (Batuk > 2 Minggu)
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Batuk Lebih dari 2 Minggu? Waspada Gejala Awal TBC',
  'batuk-lebih-dari-2-minggu-waspada-gejala-awal-tbc',
  'Batuk yang berlangsung lebih dari 2 minggu dan tidak kunjung sembuh dengan obat biasa bisa jadi tanda awal TBC. Jangan anggap remeh!',
  E'Batuk adalah mekanisme alami tubuh untuk membersihkan saluran pernapasan. Batuk akibat flu atau alergi biasanya sembuh dalam 1–2 minggu. Namun, batuk yang berlangsung **lebih dari 2 minggu** dan tidak membaik dengan obat batuk biasa harus diwaspadai sebagai kemungkinan gejala TBC.\n\n### Perbedaan Batuk Biasa dan Batuk TBC\n\n| Aspek | Batuk Biasa | Batuk TBC |\n|-------|------------|------------|\n| Durasi | < 2 minggu | > 2 minggu |\n| Dahak | Bening/kuning | Kuning kehijauan / berdarah |\n| Demam | Ringan, singkat | Meriang lama (>1 bulan) |\n| Berat badan | Stabil | Turun drastis |\n| Keringat malam | Jarang | Sering |\n| Respons obat batuk | Membaik | Tidak membaik |\n\n### Kenapa Batuk TBC Bisa 2 Minggu Lebih?\n\nBakteri TB menyebabkan peradangan kronis di jaringan paru-paru. Tubuh terus berusaha mengeluarkan bakteri dan lendir yang menumpuk, sehingga batuk menjadi respons yang terus-menerus. Tidak seperti virus flu yang bisa ditangani sistem imun dalam beberapa hari, bakteri TB memerlukan pengobatan antibiotik khusus untuk diatasi.\n\n### Apa yang Harus Dilakukan?\n\nJika kamu atau orang terdekat mengalami batuk >2 minggu:\n\n1. **Kunjungi puskesmas terdekat** — Gratis dan tidak perlu takut\n2. **Minta pemeriksaan dahak** — Tes BTA (Basil Tahan Asam) atau TCM (Tes Cepat Molekuler)\n3. **Lakukan rontgen dada** jika diperlukan dokter\n4. **Jangan tunda** — Semakin cepat diperiksa, semakin baik\n\n### Stigma yang Harus Dihilangkan\n\nBanyak orang enggan periksa karena takut divonis TBC dan dikucilkan. Ingat: TBC adalah penyakit biasa yang **bisa disembuhkan**. Tidak ada yang perlu dipermalukan. Justru keberanian untuk memeriksakan diri adalah tindakan bertanggung jawab.',
  2, 3, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 7: Pencegahan TBC (Pola Makan)
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Pola Makan Sehat untuk Meningkatkan Imun Melawan TBC',
  'pola-makan-sehat-untuk-meningkatkan-imun-melawan-tbc',
  'Nutrisi yang baik adalah fondasi sistem imun yang kuat. Pelajari pola makan yang tepat untuk membantu tubuh melawan infeksi TBC.',
  E'Sistem imun yang kuat adalah pertahanan utama tubuh terhadap infeksi TBC. Malnutrisi dan kekurangan gizi adalah salah satu faktor risiko utama yang membuat seseorang lebih rentan terhadap TBC dan menghambat proses pemulihan.\n\n### Hubungan Nutrisi dan TBC\n\nPenelitian menunjukkan bahwa **kekurangan gizi meningkatkan risiko TBC hingga 3 kali lipat**. Sebaliknya, penderita TBC yang mendapat nutrisi cukup memiliki respons yang lebih baik terhadap pengobatan dan lebih cepat pulih.\n\n### Nutrisi Penting untuk Imunitas\n\n**Protein (Pembangun Antibodi)**\n- Sumber: telur, ikan, daging ayam, tempe, tahu, kacang-kacangan\n- Fungsi: membangun sel imun dan memperbaiki jaringan yang rusak\n- Target: minimal 1.2–1.5 gram protein per kg berat badan per hari\n\n**Vitamin A (Pelindung Mukosa)**\n- Sumber: wortel, ubi jalar, bayam, hati ayam, telur\n- Fungsi: menjaga kesehatan lapisan mukosa saluran pernapasan\n\n**Vitamin C (Antioksidan)**\n- Sumber: jeruk, jambu biji, kiwi, paprika merah, brokoli\n- Fungsi: meningkatkan aktivitas sel imun dan mengurangi peradangan\n\n**Vitamin D (Modulator Imun)**\n- Sumber: sinar matahari pagi, ikan salmon, susu fortifikasi, telur\n- Fungsi: mengaktifkan sel imun yang melawan bakteri TB\n- Berjemur 10–15 menit setiap pagi sangat dianjurkan\n\n**Zinc (Mineral Imun)**\n- Sumber: daging merah, biji labu, kacang mete, biji-bijian\n- Fungsi: penting untuk perkembangan dan fungsi sel imun\n\n**Zat Besi**\n- Sumber: daging merah, bayam, kacang merah, hati sapi\n- Catatan: penderita TBC sering mengalami anemia, zat besi sangat penting\n\n### Makanan yang Perlu Dihindari\n\n❌ Alkohol — melemahkan sistem imun secara signifikan\n❌ Rokok — merusak lapisan mukosa paru-paru\n❌ Makanan ultra-proses — tinggi gula dan rendah nutrisi\n❌ Kafein berlebihan — mengganggu penyerapan zat besi\n\n### Contoh Menu Harian\n\n**Pagi:** Nasi + telur ceplok + sayur bayam + jeruk\n**Siang:** Nasi + ikan panggang + tempe goreng + tumis kangkung + air putih\n**Sore:** Buah pisang / pepaya + susu\n**Malam:** Nasi + ayam kampung + sup sayuran + tahu\n\n> Konsultasikan kebutuhan gizi spesifik kamu dengan ahli gizi jika sedang dalam masa pengobatan TBC.',
  4, 4, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 8: Sosialisasi & Stigma
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Menghapus Stigma TBC: Sakit Bukan Aib, Sembuh Itu Bisa!',
  'menghapus-stigma-tbc-sakit-bukan-aib-sembuh-itu-bisa',
  'Stigma negatif terhadap penderita TBC masih menjadi penghalang utama deteksi dini dan pengobatan. Saatnya kita ubah cara pandang bersama.',
  E'Di banyak komunitas, label "TBC" masih membawa stigma yang berat. Penderita TBC sering dikucilkan, kehilangan pekerjaan, atau dijauhi keluarga. Ironisnya, stigma ini justru memperburuk situasi karena membuat orang enggan memeriksakan diri, yang pada akhirnya memperpanjang rantai penularan.\n\n### Fakta vs Mitos tentang TBC\n\n**MITOS:** TBC adalah penyakit orang miskin\n**FAKTA:** TBC bisa menyerang siapa saja tanpa memandang status ekonomi. Tokoh-tokoh bersejarah seperti Frédéric Chopin dan George Orwell pun pernah menderita TBC.\n\n**MITOS:** TBC tidak bisa disembuhkan\n**FAKTA:** TBC BISA DISEMBUHKAN dengan pengobatan OAT yang tepat dan teratur selama 6–9 bulan. Tingkat kesembuhan TBC sensitif obat sangat tinggi.\n\n**MITOS:** Penderita TBC harus diisolasi selamanya\n**FAKTA:** Setelah 2 minggu pengobatan, penderita TBC umumnya sudah tidak menular dan bisa kembali beraktivitas normal.\n\n**MITOS:** TBC menular hanya dengan kontak biasa\n**FAKTA:** TBC menular melalui udara (droplet), bukan lewat jabat tangan, berbagi makanan, atau menyentuh benda yang sama.\n\n### Dampak Stigma pada Penanganan TBC\n\n- Penderita menunda atau menghindari pemeriksaan\n- Pasien berhenti pengobatan karena malu atau takut dikucilkan\n- Keluarga menyembunyikan diagnosis anggota keluarga yang sakit\n- Keterlambatan penanganan meningkatkan risiko kematian dan penularan\n\n### Apa yang Bisa Kita Lakukan?\n\n**Sebagai individu:**\n- Edukasi diri sendiri tentang fakta TBC\n- Tunjukkan empati dan dukungan kepada penderita\n- Tidak menyebarkan informasi yang salah tentang TBC\n\n**Sebagai keluarga/teman penderita:**\n- Ingatkan dan bantu penderita untuk minum obat teratur (jadilah PMO)\n- Jaga privasi diagnosis anggota keluarga\n- Dukung secara emosional — penderita TBC butuh dukungan, bukan penghakiman\n\n**Sebagai masyarakat:**\n- Dukung program pemberantasan TBC pemerintah\n- Laporkan fasilitas kesehatan yang tidak ramah kepada penderita TBC\n- Bagikan informasi yang akurat tentang TBC di media sosial\n\n> **Ingat:** Penderita TBC yang sedang berobat adalah pahlawan — mereka melindungi diri sendiri dan orang lain. Dukung mereka, jangan singkirkan.',
  6, 4, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 9: Gejala TBC pada Anak
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'TBC pada Anak: Kenali Tanda-tandanya Sebelum Terlambat',
  'tbc-pada-anak-kenali-tanda-tandanya-sebelum-terlambat',
  'TBC pada anak memiliki gejala yang berbeda dari orang dewasa dan lebih sulit dideteksi. Kenali tanda-tandanya agar si kecil mendapat pertolongan segera.',
  E'TBC pada anak adalah kondisi serius yang memerlukan perhatian khusus. Berbeda dengan orang dewasa, gejala TBC pada anak seringkali tidak spesifik dan mudah terlewat.\n\n### Perbedaan TBC Anak dan Dewasa\n\n| Aspek | TBC Dewasa | TBC Anak |\n|-------|------------|----------|\n| Batuk | Batuk berdahak >2 minggu | Batuk lama, bisa tidak berdahak |\n| Penularan | Sering menjadi sumber penularan | Jarang menjadi sumber penularan |\n| Diagnosis | Tes dahak (BTA) | Sistem skoring (karena dahak sulit diambil) |\n| Pengobatan | OAT standar 6 bulan | OAT disesuaikan berat badan |\n\n### Gejala TBC pada Anak\n\n- Berat badan tidak naik atau turun dalam 3 bulan terakhir tanpa sebab jelas\n- Demam lama dan berulang (lebih dari 2 minggu) yang tidak jelas penyebabnya\n- Batuk lama lebih dari 2 minggu yang tidak membaik\n- Muncul benjolan di leher, ketiak, atau selangkangan (pembesaran kelenjar getah bening)\n- Anak terlihat lesu, tidak aktif, dan mudah lelah\n- Diare berkepanjangan yang tidak sembuh dengan obat biasa\n- Keringat berlebihan di malam hari\n\n### Diagnosis TBC Anak\n\nKarena dahak anak sulit dikumpulkan, dokter menggunakan **Sistem Skoring TB Anak** yang mempertimbangkan:\n- Kontak dengan penderita TBC dewasa\n- Gejala klinis yang ada\n- Hasil uji tuberkulin (mantoux test)\n- Foto rontgen dada\n- Kondisi gizi anak\n\n### Pencegahan TBC pada Anak\n\n1. **Vaksinasi BCG** pada bayi baru lahir (program imunisasi nasional)\n2. **Pemeriksaan kontak** — Jika ada anggota keluarga yang TBC, anak di bawah 5 tahun WAJIB diperiksa\n3. **Terapi Preventif TB (TPT)** — Anak balita yang kontak erat dengan penderita TBC aktif diberikan isoniazid profilaksis oleh dokter\n4. **Nutrisi optimal** — ASI eksklusif 6 bulan, MPASI bergizi, hindari malnutrisi',
  2, 4, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 10: MDR-TB
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Mengenal MDR-TB: TBC Kebal Obat yang Perlu Diwaspadai',
  'mengenal-mdr-tb-tbc-kebal-obat-yang-perlu-diwaspadai',
  'MDR-TB (Multi-Drug Resistant TB) adalah TBC yang sudah kebal terhadap obat utama. Kondisi ini lebih sulit diobati dan terjadi akibat pengobatan yang tidak tuntas.',
  E'MDR-TB (Multi-Drug Resistant Tuberculosis) adalah bentuk TBC yang telah mengembangkan resistensi terhadap dua obat anti-TB lini pertama yang paling kuat, yaitu Isoniazid dan Rifampisin. MDR-TB adalah krisis kesehatan global dan tantangan terbesar dalam pemberantasan TBC.\n\n### Bagaimana MDR-TB Terjadi?\n\nMDR-TB berkembang ketika pasien TBC tidak menyelesaikan pengobatan dengan benar:\n- Berhenti minum obat sebelum waktunya karena merasa sudah sembuh\n- Mengonsumsi dosis yang salah\n- Kualitas obat yang buruk\n- Tidak teratur minum obat (melewatkan banyak dosis)\n\nSisa bakteri yang masih hidup beradaptasi dan mengembangkan mekanisme pertahanan terhadap obat — inilah resistensi.\n\n### Seberapa Serius MDR-TB?\n\n- Pengobatan MDR-TB jauh lebih panjang: **18–24 bulan** (dibanding 6 bulan TBC biasa)\n- Obat yang digunakan lebih banyak, lebih mahal, dan lebih banyak efek samping\n- Angka kesembuhan lebih rendah\n- Risiko penularan ke orang lain tetap ada\n\n### Gejala MDR-TB\n\nGejala MDR-TB sama dengan TBC biasa, namun:\n- Tidak membaik setelah pengobatan TBC standar\n- Bakteri tetap terdeteksi dalam dahak setelah 2 bulan pengobatan\n- Konfirmasi MDR-TB melalui tes resistensi obat (DST/Drug Susceptibility Testing) atau TCM\n\n### Pencegahan MDR-TB\n\n✅ **Selesaikan pengobatan TBC tanpa putus** — Ini adalah pencegahan utama\n✅ Ikuti petunjuk dokter dan petugas kesehatan\n✅ Minta bantuan PMO (Pengawas Minum Obat) dari keluarga\n✅ Laporkan jika ada efek samping — jangan berhenti obat sendiri\n✅ Kontrol rutin ke fasilitas kesehatan sesuai jadwal',
  5, 5, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 11: PMO
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'Peran PMO (Pengawas Minum Obat) dalam Kesembuhan Pasien TBC',
  'peran-pmo-pengawas-minum-obat-dalam-kesembuhan-pasien-tbc',
  'PMO adalah orang yang memastikan pasien TBC minum obatnya setiap hari. Peran ini krusial dalam mencegah pengobatan putus dan mencegah MDR-TB.',
  E'Strategi DOTS (Directly Observed Treatment Short-Course) yang direkomendasikan WHO mewajibkan adanya **PMO (Pengawas Minum Obat)** untuk setiap pasien TBC. PMO adalah orang terpercaya yang bertugas memastikan pasien minum obat setiap hari dan memantau kondisi pasien selama masa pengobatan.\n\n### Siapa yang Bisa Menjadi PMO?\n\n- Anggota keluarga yang tinggal serumah (suami, istri, orang tua, anak dewasa)\n- Kader kesehatan di lingkungan\n- Petugas puskesmas\n- Tetangga yang dipercaya\n\nSyarat PMO: dipercaya pasien, tinggal dekat dengan pasien, mau dilatih oleh petugas kesehatan.\n\n### Tugas dan Tanggung Jawab PMO\n\n1. **Mengawasi** pasien minum OAT setiap hari (DOTS)\n2. **Memotivasi** pasien agar tidak putus obat\n3. **Mengingatkan** jadwal kontrol ke puskesmas/rumah sakit\n4. **Memantau** gejala dan efek samping obat\n5. **Segera menghubungi** petugas kesehatan jika pasien berhenti minum obat atau kondisi memburuk\n6. **Merahasiakan** kondisi pasien dari pihak lain yang tidak berkepentingan\n\n### Manfaat PMO\n\nPenelitian menunjukkan bahwa pasien TBC dengan PMO yang aktif memiliki:\n- Tingkat kepatuhan minum obat yang jauh lebih tinggi\n- Angka kesembuhan yang lebih baik\n- Risiko MDR-TB yang lebih rendah\n- Dukungan psikologis yang membantu proses pemulihan\n\n### Tips Menjadi PMO yang Efektif\n\n💙 Jadilah pendengar yang baik — pasien mungkin merasa frustrasi\n💙 Ingatkan dengan cara yang positif, bukan memaksa\n💙 Rayakan setiap pencapaian — 1 bulan selesai, 3 bulan selesai, dst.\n💙 Jaga kerahasiaan diagnosis pasien\n💙 Ajak pasien kontrol bersama ke puskesmas',
  5, 3, FALSE
) ON CONFLICT (slug) DO NOTHING;

-- Article 12: TBC dan HIV
INSERT INTO articles (title, slug, excerpt, content, category_id, read_time_minutes, is_featured) VALUES
(
  'TBC dan HIV: Mengapa Kombinasi Ini Sangat Berbahaya?',
  'tbc-dan-hiv-mengapa-kombinasi-ini-sangat-berbahaya',
  'Orang dengan HIV memiliki risiko jauh lebih tinggi untuk mengembangkan TBC aktif. Memahami hubungan keduanya penting untuk penanganan yang tepat.',
  E'TBC dan HIV adalah dua penyakit yang saling memperburuk satu sama lain — kondisi yang dikenal sebagai **ko-infeksi TB-HIV**. Di seluruh dunia, TBC adalah penyebab kematian nomor satu pada orang yang hidup dengan HIV (ODHIV).\n\n### Mengapa ODHIV Sangat Rentan terhadap TBC?\n\nHIV menyerang dan merusak sel CD4 (sel T helper), yang merupakan komponen kunci sistem imun. Ketika jumlah sel CD4 menurun, kemampuan tubuh untuk melawan infeksi — termasuk bakteri TB — berkurang drastis.\n\nOrang sehat yang terinfeksi bakteri TB memiliki risiko sekitar 5–10% seumur hidup untuk berkembang menjadi TBC aktif. Namun, **ODHIV yang terinfeksi TB memiliki risiko 10–30 kali lebih tinggi** untuk mengembangkan TBC aktif setiap tahunnya.\n\n### Tantangan Diagnosis Ko-Infeksi TB-HIV\n\nGejala TBC pada ODHIV seringkali atipikal (tidak biasa):\n- Foto rontgen dada bisa tampak normal meski ada TBC aktif\n- Tes dahak BTA bisa negatif palsu\n- TBC Ekstra Paru lebih sering terjadi\n- Gejala tumpang tindih dengan infeksi oportunistik lainnya\n\n### Penanganan Ko-Infeksi TB-HIV\n\n1. **TBC didiagnosis dulu** — Mulai pengobatan OAT segera\n2. **ARV (Antiretroviral)** — Mulai dalam 2–8 minggu setelah OAT dimulai (bukan setelah selesai)\n3. **Terapi Preventif TB** — Semua ODHIV yang tidak memiliki TBC aktif harus mendapat IPT (Isoniazid Preventive Therapy)\n4. **Monitoring ketat** — Interaksi obat OAT dan ARV perlu dipantau dokter secara rutin\n\n> Jika kamu atau orang yang kamu kenal adalah ODHIV, sangat penting untuk rutin melakukan skrining TBC minimal sekali setahun.',
  1, 4, FALSE
) ON CONFLICT (slug) DO NOTHING;
